#cloud-config
package_update: true
package_upgrade: true

users:
  - name: sysadmin
    ssh-authorized-keys:
      - {{ .SSHKey}}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

hostname: {{ .Hostname }}
manage_etc_hosts: localhost

bootcmd:
  - sed -i 's/\/\/\t"${distro_id}:${distro_codename}-updates";/\t"${distro_id}:${distro_codename}-updates";/g' /etc/apt/apt.conf.d/50unattended-upgrades
  - bash -c "echo >> /etc/apt/apt.conf.d/50unattended-upgrades"
  - bash -c "echo 'Unattended-Upgrade::Remove-Unused-Dependencies \"true\";' >> /etc/apt/apt.conf.d/50unattended-upgrades"
  - bash -c "echo 'Unattended-Upgrade::Remove-Unused-Kernel-Packages \"true\";' >> /etc/apt/apt.conf.d/50unattended-upgrades"
  - bash -c "echo 'Unattended-Upgrade::Automatic-Reboot-Time \"04:00\";' >> /etc/apt/apt.conf.d/50unattended-upgrades"
  - bash -c "echo 'Unattended-Upgrade::Automatic-Reboot \"true\";' >> /etc/apt/apt.conf.d/50unattended-upgrades"
